# Generated by Django 4.0.1 on 2024-03-11 07:28

from django.db import migrations, models
import django.db.models.deletion
import posts.validates_function


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500, validators=[posts.validates_function.validate_comment_length])),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[posts.validates_function.validate_title_length])),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('post_image', models.ImageField(upload_to='post_images/', validators=[posts.validates_function.validate_image_size])),
            ],
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_post', to='posts.post')),
            ],
        ),
    ]
