# Generated by Django 4.0.1 on 2024-03-15 02:33

import chat.validate_function_for_chat
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'db_table': 'chat_message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_user_is_writing', models.BooleanField(default=False)),
                ('second_user_is_writing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat Room',
                'db_table': 'chat_room',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message/', validators=[chat.validate_function_for_chat.validate_file])),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_image', models.ImageField(blank=True, null=True, upload_to='message_image/')),
            ],
            options={
                'verbose_name': 'Message File Model',
                'db_table': 'file_model',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('group_image', models.ImageField(blank=True, null=True, upload_to='group/image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Group Chat',
                'db_table': 'group_chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Group Chat Message',
                'db_table': 'group_chat_message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
                ('message_type', models.CharField(choices=[('word', 'word'), ('pdf', 'pdf'), ('excel', 'excel'), ('image', 'image'), ('video', 'video'), ('voice', 'voice'), ('text', 'text'), ('story', 'story'), ('forward_message', 'forward_message'), ('forward_post', 'forward_post')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forward_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward_chat_message', to='chat.message')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'db_table': 'message',
                'ordering': ['-created_at'],
            },
        ),
    ]
