# Generated by Django 4.0.1 on 2024-03-12 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='file_type',
            new_name='message_type',
        ),
        migrations.AddField(
            model_name='message',
            name='forward_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward_chat_message', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='forward_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forward_post_message', to='posts.post'),
        ),
    ]
