# Generated by Django 4.0.1 on 2024-03-12 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('chat', '0003_rename_file_type_message_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('document', 'document'), ('image', 'image'), ('video', 'video'), ('voice', 'voice'), ('text', 'text'), ('story', 'story'), ('forward_message', 'forward_message'), ('forward_post', 'forward_post')], max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_story_message', to='users.story'),
        ),
    ]
