# Generated by Django 4.0.1 on 2024-03-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_message_type_alter_message_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='chat',
            new_name='chat_room',
        ),
    ]
