# Generated by Django 4.0.1 on 2024-03-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_chat_chatmessage_chat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('word', 'word'), ('pdf', 'pdf'), ('excel', 'excel'), ('image', 'image'), ('video', 'video'), ('voice', 'voice'), ('text', 'text'), ('story', 'story'), ('forward_message', 'forward_message'), ('forward_post', 'forward_post')], max_length=15),
        ),
    ]
