# Generated by Django 4.0.1 on 2024-03-16 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.IntegerField(choices=[(0, 'LIKE'), (1, 'FOLLOWING'), (2, 'CHAT'), (3, 'COMMENT'), (4, 'STORY')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('following_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_following_user', to=settings.AUTH_USER_MODEL)),
                ('notification_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_chat', to='chat.chatroom')),
                ('notification_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_comment', to='posts.commentpost')),
                ('notification_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_story', to='users.userstory')),
                ('notification_visible_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_visible_to_user', to=settings.AUTH_USER_MODEL)),
                ('post_like', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_post_like', to='posts.post')),
            ],
        ),
    ]
