# Generated by Django 4.0.1 on 2024-03-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
